name: passphrase_generator
description: A Dart package for generating passphrases with any length.
  The passphrase can be in string form or in list form.
version: 0.1.3
repository: https://github.com/thecasualdev17/passphrase_generator

environment:
  sdk: ^3.7.2

dependencies:
  word_collection_utils: ^0.1.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

assets:
  - lib/assets/collection.csv
